file = open('1.txt', 'r')
print(file.read())
file.close()
file = open('1.txt', 'r')
print("\n Read in Parts \n")
print(file.read(17))
file.close()
file
file_append = open('1.txt', 'a')
file_append.write("Later, he continued his success with Juventus in Italy and currently plays for Al-Nassr in Saudi Arabia, while also serving as captain of the Portuguese national team. Ronaldo’s playing style is marked by incredible speed, technical precision, aerial dominance, and a fierce competitive spirit. His dedication to training and fitness has allowed him to maintain top form well into his late 30s, setting an example of professionalism for younger athletes. Over his career, he has won multiple Ballon d’Or awards and broken countless records, including becoming the all-time leading goal scorer in both international football and the UEFA Champions League. Beyond his achievements on the field, Ronaldo is known for his philanthropy, charisma, and global influence, making him not only a football icon but also a symbol of hard work, ambition, and perseverance.")
file_append.close()
file = open('1.txt', 'r')
print(file.read())
file.close()
file = open('1.txt', 'r')
print("\n Read in Parts \n")
print(file.readlines(9))
file.close()